api_port: 9090
api_expvar_path: nil  # not exposed
events_buffer_size: 5
log_level: debug    # valid values: Debug, Info, Warning, Error, Fatal, Panic
apigeesync_proxy_server_base: http://local.com:9001/edgex
apigeesync_snapshot_server_base: http://local.com:9001/edgex
apigeesync_change_server_base: http://local.com:9001/edgex
apigeesync_snapshot_proto: json
apigeesync_consumer_key: MDygyE8OD8rlemI7S1XhlUCA7jrarjxl
apigeesync_consumer_secret: oAuKUqRVvFVq0tzS
apigeesync_cluster_id: fc0e5137-d3fa-4017-8bfa-86b1103bc85d
apidanalytics_uap_server_base: http://local.com:9001/edgex