# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM golang:1.8.3-stretch

# install tools
RUN apt-get update && apt-get -y install vim && curl https://glide.sh/get | sh

RUN mkdir -p /demo
WORKDIR /go/src/github.com/30x
RUN go version
# install mock_server
RUN git clone -b ISSUE-65203841 https://github.com/30x/apid.git \
 && (cd apid/load-test/mock_server; glide install -v; go build) \
 && cp apid/load-test/mock_server/mock_server /demo
WORKDIR /demo
COPY ./startMockserver.sh startMockserver.sh

EXPOSE 9001

ENTRYPOINT [ "./startMockserver.sh"]
