FROM golang:1.7-wheezy

# install tools
RUN apt-get update && apt-get -y install vim sqlite3 && curl https://glide.sh/get | sh

RUN mkdir -p /demo/data
WORKDIR /go/src/github.com/30x

# install apid
RUN git clone https://github.com/30x/apid.git \
 && (cd apid/cmd/apid; glide install) \
 && (cd apid/cmd/apid; go build) \
 && cp apid/cmd/apid/apid /demo

# install mock server
RUN (git clone https://github.com/30x/apidApigeeSync.git) \
 && (cd apidApigeeSync/; glide install) \
 && (cd apidApigeeSync/cmd/mockServer; go build) \
 && cp apidApigeeSync/cmd/mockServer/mockServer /demo

WORKDIR /demo
COPY ./apid_config.yaml apid_config.yaml
COPY ./startServices.sh startServices.sh
ENV APID_API_PORT=9001
EXPOSE 9001
#APID_API_PORT=9001 ./mockServer -numDeps=100 -numDevs=50000 -addDevEach=3s -upDevEach=1s -upDepEach=3s

ENTRYPOINT [ "./mockServer", "-numDeps=100", "-numDevs=50000", "-addDevEach=3s", "-upDevEach=1s", "-upDepEach=3s", "-bundleURI=$CLOUD_IP" ]