FROM golang:1.8.3-stretch

# install tools
RUN apt-get update && apt-get -y install vim sqlite3 && curl https://glide.sh/get | sh

RUN mkdir -p /demo/data
WORKDIR /go/src/github.com/30x
RUN go version
# install apid
RUN git clone -b ISSUE-65203841 https://github.com/30x/apid.git \
 && (cd apid; glide install) \
 && (cd apid; go build) \
 && cp apid/apid /demo
WORKDIR /demo
COPY ./apid_config.yaml apid_config.yaml
COPY ./init_base_db.sql init_base_db.sql
COPY ./init_data_db.sql init_data_db.sql
COPY ./startServices.sh startServices.sh

EXPOSE 9000

ENTRYPOINT [ "./startServices.sh"]
