FROM golang:1.8.3-stretch

# install tools
RUN apt-get update && apt-get -y install vim && curl https://glide.sh/get | sh

RUN mkdir -p /demo
WORKDIR /go/src/github.com/30x
RUN go version
# install mock_server
RUN git clone -b ISSUE-65203841 https://github.com/30x/apid.git \
 && (cd apid/load-test/mock_server; glide install -v; go build) \
 && cp apid/load-test/mock_server/mock_server /demo
WORKDIR /demo
COPY ./startMockserver.sh startMockserver.sh

EXPOSE 9001

ENTRYPOINT [ "./startMockserver.sh"]
