# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM golang:1.8.3-stretch

# install tools
RUN apt-get update && apt-get -y install vim sqlite3 && curl https://glide.sh/get | sh

RUN mkdir -p /demo/data
WORKDIR /go/src/github.com/apid
RUN go version
# install apid
RUN git clone https://github.com/apid/apid.git \
 && (cd apid; glide install -v) \
 && (cd apid; go build) \
 && cp apid/apid /demo
WORKDIR /demo
COPY ./apid_config.yaml apid_config.yaml
COPY ./base_sqlite3 base_sqlite3
COPY ./data_sqlite3 data_sqlite3
COPY ./startServices.sh startServices.sh

EXPOSE 9000

ENTRYPOINT [ "./startServices.sh"]
